# Gunakan node image untuk membangun aplikasi
FROM node:20-alpine AS build

# Tentukan direktori kerja
WORKDIR /app

# Salin file package.json dan package-lock.json
COPY package*.json ./

# Install dependensi proyek, termasuk vite
RUN npm install

# Salin semua file aplikasi
COPY . .

# Build aplikasi
RUN npm run build

# Gunakan nginx untuk menyajikan aplikasi
FROM nginx:alpine
COPY --from=build /app/dist /usr/share/nginx/html

EXPOSE 80

# Jalankan nginx
CMD ["nginx", "-g", "daemon off;"]
