# Gunakan node image untuk membangun aplikasi
FROM node:20-alpine

# Tentukan direktori kerja
WORKDIR /app

# Salin file package.json dan package-lock.json
COPY package*.json ./

# Install dependensi proyek
RUN npm install

# Salin semua file aplikasi
COPY . .

# Ekspos port aplikasi
EXPOSE 80

# Jalankan aplikasi dalam mode development
CMD ["npm", "run", "dev"]